### PR TITLE
virtual_machine_management_guide: fix title levels

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Changes proposed in this pull request:

 - Fixes:
```
asciidoctor: WARNING: topics/Powering_on_a_virtual_machine.adoc: line 2: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: topics/Opening_a_console_to_a_virtual_machine.adoc: line 2: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: topics/Opening_a_Serial_Console_to_a_Virtual_Machine.adoc: line 2: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: topics/Automatically_connecting_to_a_Virtual_Machine.adoc: line 2: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: topics/Installing_Windows_on_Virtio_Optimized_Hardware.adoc: line 2: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: topics/Opening_a_Console_to_a_Virtual_Machine.adoc: line 2: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: topics/Configuring_operating_systems_with_osinfo.adoc: line 2: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: chap-Additional_Configuration.adoc: line 7: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: chap-Additional_Configuration.adoc: line 30: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: chap-Additional_Configuration.adoc: line 53: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: chap-Additional_Configuration.adoc: line 60: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: chap-Additional_Configuration.adoc: line 101: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: topics/Configuring_virtual_NUMA.adoc: line 2: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: topics/Configuring_Satellite_Errata.adoc: line 2: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: topics/Configuring_Headless_Machines.adoc: line 2: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: topics/Configuring_high_performance_virtual_machines.adoc: line 2: section title out of sequence: expected level 2, got level 3
```

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sandrobonazzola 

This pull request needs review by: @stoobie

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
Rendered page:

**Review by stoobie — CHANGES_REQUESTED** [review]
In general, it's best to indicate hierarchy in an assembly. If these are all the top-level headings in each topic, I would make them all heading 1 (e.g. `= Configuring Operating Systems with osinfo`) and update the assembly files with the correct hierarchy like this: 
`include::topics/Configuring_operating_systems_with_osinfo.adoc[leveloffset=+1]` (or if it's currently set to `=== <title>`, then change the title to `= <title>` and the assembly to `leveloffset=+2`.



Doing it this way enables better content reuse.

**Comment by sandrobonazzola** [comment]
@stoobie I pushed an update addressing your comment, can you please review again?

**Review by stoobie — APPROVED** [review]
LGTM, but I just noticed that there are two redundant files. Not sure why. I opened BZ#1894422 to deal with this, but that's not part of this PR. So go ahead and merge.

**Pull request merged**
