### PR TITLE
Minor type fix in virtio-scsi

### PR DESCRIPTION
**Pull request by mz-pdm**

### CODE REVIEW

**Comment by mureinik** [comment]
+1

**Comment by mykaul** [comment]
:+1:

**Comment by mureinik** [comment]
@thatdocslady / @sandrobonazzola  Can this be merged please?

**Comment by mykaul** [comment]
@mureinik  - I thought I did ?

**Comment by mureinik** [comment]
@mykaul arg, I must have been looking at the wrong window. Thanks, and sorry for noise.

**Pull request merged**
