### PR TITLE
Released oVirt 4.0.4

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Changes proposed in this pull request:

- Updated release notes for 4.0.4 GA

I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @sandrobonazzola

This pull request needs review by: @rafaelmartins

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
Holding merge until the repositories are ready: :-1:

**Comment by rafaelmartins** [comment]
:+1:

**Comment by sandrobonazzola** [comment]
Holding a bit more due to a possible blocker bug :-1:

**Comment by sandrobonazzola** [comment]
RPMs released

**Pull request merged**
