### PR TITLE
new commit for blog post 411

### PR DESCRIPTION
**Pull request by JohnMarksRH**
Fixes issue # (delete if not relevant)

Changes proposed in this pull request: I have resubmitted the 4.1.1 blog post, this time with the correct filename format. I have changed the subheadings from "##" - which look the same size as the title - to "###". This time I previewed the post on middleman (. ./run-server.sh). This PR is associated with PR # 894. 

-

-

-

I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @jmarks

This pull request needs review by: @bproffitt @mykaul

### CODE REVIEW

**Comment by duck-rh** [comment]
The link on #894 did not show up for some reason (seem there is a space after #)

**Comment by JohnMarksRH** [comment]
This PR is associated with https://github.com/oVirt/ovirt-site/pull/894

**Comment by duck-rh** [comment]
So, the problem with doing two things in the same PR is that things are mixed and you have to either agree on all changes to merge or block until everything is fine.

So the renaming is fine.

But the proposed change in the headers are not right AFAIK. If there is a costemic problem with level 2 headings, then the CSS should be improved. Heading levels are meant to organize titles in a tree and this breaks the semantic (and removes one possible depth level which could be useful in some pages).

So I'm in favour of staying with the current headings usage and rejecting this change, sorry.

**Comment by mykaul** [comment]
We can fix the CSS later, let's get the blog entry up. 
I agree in general we should not perform several unrelated changes in a single PR of course.

**Comment by duck-rh** [comment]
@mykaul, I suggested to isolate the renaming in another PR I would have merged right away, but @JohnMarksRH refused.

I think the headings change is wrong and it is unneeded to get the blog entry in anyway, so I'm not going to accept a bunch of unrelated changes with one I disagree upon.

**Comment by mykaul** [comment]
You are mostly correct, but due to the holidays, I wanted the blog post to come out ASAP.

**Comment by duck-rh** [comment]
Creating a new PR and approving it would have taken 2 minutes at most, so this is totally irrelevant.

The fact you have a deadline does not mean you can violate the contribution policy. This place is for open contribution on the oVirt's website, which means respect and cooperation with other contributors.
Disputed changes were slipped in for no good reason, please fix this ASAP.

**Pull request merged**
