### PR TITLE
Update chap-Administrative_Tasks.md

### PR DESCRIPTION
**Pull request by lisamichele-oracle**
propose change from 'slave' to 'subordinate' to eliminate insensitive term

Fixes issue # (delete if not relevant)

Changes proposed in this pull request:

-

-

-

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @mention yourself to sign)

This pull request needs review by: (please @mention the reviewer if relevant)

### CODE REVIEW

**Comment by lisamichele-oracle** [comment]
@lisamichele-oracle

**Comment by lisamichele-oracle** [comment]
@gregsheremeta

**Comment by gregsheremeta** [comment]
I'm not actively participating in currently, so I defer to @sandrobonazzola

**Comment by sandrobonazzola** [comment]
Thanks @lisamichele-oracle I appreciate the intention. @dominikholler is there any problem using "subordinate" instead of "slave" referring to vNICs added to an 'active-backup' bond?
I see that in `ip link show` the word SLAVE is used to identify such  vNICs and despite I would love to eliminate an insensitive term from our documentation I wonder if we need to wait for ip command to adjust their output before we change the term here.

**Comment by dominikholler** [comment]
> Thanks @lisamichele-oracle I appreciate the intention.

Ack, it is worth to discuss.

> @dominikholler is there any problem using "subordinate" instead of
> "slave" referring to vNICs added to an 'active-backup' bond?

To avoid confusion, I vote to be consistent.
I the first place consistency inside oVirt,
in the second place consistency in the Linux ecosystem.

For this reason I would wait until the new wording of the Linux kernel,
e.g. in
https://www.kernel.org/doc/Documentation/networking/bonding.txt .
is known, and have a consistent change in oVirt from the old wording to
the new wording.

**Comment by DevAlone** [comment]
Thanks for the inspiration, I'll rename my basement slaves to subordinates, hope it's gonna help, cuz these naughty bastard just don't want to work!

**Comment by stoobie** [comment]
Just want to note that this is a company-wide grassroots initiative at Red Hat. I suggest that we come up with consistent terminology across the product portfolio.

**Comment by sandrobonazzola** [comment]
closing due to inactivity, please reopen if you start working again on this PR

**Pull request closed without merging**
