### PR TITLE
Add Table Of Contents to 4.1.1 release notes

### PR DESCRIPTION
**Pull request by didib**
Fixes issue #898 

Changes proposed in this pull request:

-

-

-

I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (please @mention yourself to sign)

This pull request needs review by: (please @mention the reviewer if relevant)

### CODE REVIEW

**Comment by mykaul** [comment]
I'm not sure the data/events should be included here. Otherwise LGTM.

**Comment by didib** [comment]
Ran git submodule update, amended and pushed again. I still see a change in data/events, not sure that's expected/intended. @garrett @bproffitt ?
Perhaps README/CONTRIBUTING/MAINTAINING should be updated to explain how data/events should be handled (if at all) by casual contributors updating the web site content.

**Comment by didib** [comment]
Updated as requested by @duck-rh to only include the page.

I agree about wishing to have toc for all release notes pages, even most other pages, that's why I opened #181, but didn't have time yet to look at it myself.

**Comment by didib** [comment]
Added toc to all pages with 'category: documentation'. This includes all release notes pages and a few others.

**Comment by didib** [comment]
We can probably extend this to more pages, but I'd rather not break too much stuff at once...

**Comment by didib** [comment]
@duck-rh , good for you?

**Comment by JohnMarksRH** [comment]
@mykaul @duck-rh @didib @eldan 
The table of contents is a welcomed enhancement. However, it needs to be implemented in a way that enhances usability and makes the site more inviting to visitors. I think the implemented solution takes up too much space and to some extent aggravates the issue it attempts to resolve.

A couple of suggestions for improvement:
1. Something along the lines of Red Hat Documentation, but enhanced so that the menu is collapsible and floating: https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.1/html/installation_guide/chap-system_requirements

2. A simplified version of the TOC, with just the main sections (1.2.3. etc), so that it takes up less space.

Eldan, what do you think?

**Comment by duck-rh** [comment]
I tend to agree with @JohnMarksRH . Not sure we want a side TOC for all pages where a TOC makes sense but at least for documentation pages it could be nice. I also agree with not displaying every levels.

We should give a try changing the toc layout. A syntax like `{:toc max_level=3 }` might work according to the Internet (untested).

The menu would be a much more complex work I guess. As there are plans to possibly change builder, I'm not sure it is worth spending too much time on this right now.

**Comment by JohnMarksRH** [comment]
@duck-rh Sounds good. Thanks

**Comment by JohnMarksRH** [comment]
@didib @duck-rh @mykaul Further to our conversation on the TOC, can we adjust this  enhancement so that it just includes just the first level
So with this page: http://www.ovirt.org/documentation/quickstart/quickstart-guide/ we would just have the main headings 1-5. Thanks

**Comment by duck-rh** [comment]
I don't have time to work on this. I suggested a method to try, so if it works it should not be too difficult. We may have to split the layout if various kind of pages would be better with a different max level.

If you happen to create a WIP PR I could take a few minutes to review.

**Pull request merged**
