### PR TITLE
Remove some project ideas that were implemented already

### PR DESCRIPTION
**Pull request by mykaul**
Changes proposed in this pull request:

- Remove GSOC ideas that were implemented / irrelevant.

I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @mykaul

This pull request needs review by: (please @mention the reviewer if relevant)
@JohnMarksRH

### CODE REVIEW

**Comment by JohnMarksRH** [comment]
Suggest "Remove GSOC ideas that were either implemented or irrelevant."

**Comment by JohnMarksRH** [comment]
@mykaul, would you like me to review and language edit the texts?

**Comment by mykaul** [comment]
Just regular review for my patch.

**Comment by JohnMarksRH** [comment]
@mykaul looks good. Some minor language edits could help to make it a little easier to read.

**Comment by sandrobonazzola** [comment]
@mykaul can you please rebase?

**Comment by gregsheremeta** [comment]
no longer relevant, closing

**Pull request closed without merging**
