### PR TITLE
Add new oVirt 4.0 documentation

### PR DESCRIPTION
**Pull request by bproffitt**
Changes proposed in this pull request:

- Added new oVirt 4.0 documentation based on RHV 4.0 docs

I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @bproffitt

### CODE REVIEW

**Comment by bproffitt** [comment]
@garrett @duck-rh @mscherer Looking at the Travis logs, it looks like it is checking for the existence of an index.html file in folders I created in the /documentation directory. There are no such files, and there does not need to be; all of my changes are working perfectly in my local middleman instance and I am 99% sure this is ready to merge. But on the off chance it isn't that, I thought I would ask for input.

**Comment by mscherer** [comment]
You can merge, if it doesn't build, it will not deploy anything.

**Comment by bproffitt** [comment]
@mscherer Can it build without passing these checks?

**Comment by mscherer** [comment]
Ok so I can reproduce the issue on my laptop now. That's quite curious. I will dig into it

**Pull request merged**
