### PR TITLE
developer-guide/engine/otopi: Add Logs

### PR DESCRIPTION
**Pull request by didib**
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @didib

### CODE REVIEW

**Comment by gregsheremeta** [comment]
@didib please fix up your PR message

**Comment by didib** [comment]
> @didib please fix up your PR message

Changed the subject.

Actually I wasn't happy with it either, but the current subject was more than the 50 expected chars...

If you want more/changed material (such as a message body), please propose. Thanks. Not sure commit messages are that important for such patches, where the patch itself self-describes itself much better than a commit message. IMHO... Thanks for the review, anyway :-)

**Comment by gregsheremeta** [comment]
commit message was good :) the PR message has an empty bullet list and you didn't sign. (Scroll up, edit.)

Are we not doing that? Sorry, I'm new here.

**Comment by didib** [comment]
> commit message was good :) the PR message has an empty bullet list and you didn't sign. (Scroll up, edit.)

OK, now I understand :-)

> 
> Are we not doing that? Sorry, I'm new here.

Not sure - I never did so far, and was never notified about that...

Will now, I think it makes sense.

**Comment by gregsheremeta** [comment]
> makes sense

thanks, I think it's a github standard :)

**Pull request merged**
