### PR TITLE
added site stats

### PR DESCRIPTION
**Pull request by duck-rh**

### CODE REVIEW

**Comment by garrett** [comment]
Oh. I thought it was just mirroring the stats dashboard before, and that we agreed on just using a redirect... not about porting the community dashboard over to oVirt.

**Comment by duck-rh** [comment]
On 06/22/2016 05:19 PM, Garrett LeSage wrote:
> Oh. I thought it was just mirroring the stats dashboard before, and that
> we agreed on just using a redirect... not about porting the community
> dashboard over to oVirt.

I began my work on it before your replies. I don's know how we're
suppose to mirror it, but I though the festures Misc did were sufficient.

As for the porting, it is very simple, and when I've got the access I'll
submit a PR to have a cleaner separation of code/config anyway on the
community site, and you'll see it is very very simple changes.

**Comment by thatdocslady** [comment]
@duck-rh any news wrt this?

**Comment by duck-rh** [comment]
I submited a PR for the separation of code/config on the community site, don't remember if it is merged yet.

As for this PR, it is a matter a preference and the decision is not mine.

**Pull request merged**
