### PR TITLE
Created maintainers guide for ovirt github site

### PR DESCRIPTION
**Pull request by thatdocslady**
This document describes best practices and guidelines for the oVirt site maintainers.

### CODE REVIEW

**Comment by thatdocslady** [comment]
Note: Also tweaked the general contribution guidelines to better sign-post cloning and forking.

**Comment by duck-rh** [comment]
Overall I find this a clear and not too long documentation.

The only remark I would have is: why urging people to always fork? Obviously if they don't have any access that's their only option, but for regular contributors syncing a fork is really boring. Also it make these contributions scattered instead of giving visibility of WIP work (not yet PRs). With the recent change to disallow direct push into master (see ML), then there is no mistake possible. So I would let the possibility to not fork as I see no drawback.

This contribution needs to be rebased ("This branch is out-of-date with the base branch"), but as it is on *your* own repository, noone else than you can do it even if this PR was to be accepted at once :-/.

**Comment by mykaul** [comment]
1. "If you choose to work offline in a text editor" ... - what is the alternative? If there's an easier way, I'm sure people would love to hear it.

2. "when you finish creating or editing content, commit your changes to a new branch" - I thought you should begin first with creating a new branch (locally), then create, edit your content, then commit?

**Comment by duck-rh** [comment]
Quack,

On 07/04/2016 04:46 PM, Yaniv Kaul wrote:
>  1.
> 
>     "If you choose to work offline in a text editor" ... - what is the
>     alternative? If there's an easier way, I'm sure people would love to
>     hear it.

I don't see the difficulty in using an editor. Also you can choose your
favorite tool, being it text-mode for graphical.

This said, if you run middleman in server mode:
  bundle exec middleman server
you can use the admin pages to edit blog posts. There is no support to
edit other pages (yet?). The exact URL to use is printed in the terminal
when you run the previous command.

>  2.
> 
>     "when you finish creating or editing content, commit your changes to
>     a new branch" - I thought you should begin first with creating a new
>     branch (locally), then create, edit your content, then commit?

Agreed, the doc must be fixed.

\_o<

**Comment by thatdocslady** [comment]
@mykaul @duck-rh the "if" statement about the text editor is addressed in the "Access the source content" section. Users have a few options: Fork+clone / click "Edit this page on GitHub" in site / click the Edit icon in GitHub.

The recommendation to fork is based on standard GitHub practices, and syncing a fork should be something that most developers who work upstream will be familiar with. Also, there have been cases (in oVirt and many other projects) where someone with commit rights accidentally merges something to master, so this is another way to prevent that.

Regarding the branches, if you work offline/locally then yes you should create a new branch first, but if you edit directly in GitHub you only need to do that when you commit, not while you edit.

**Comment by jasonbrooks** [comment]
This looks good to me, and if we need to change something... we can do that!

**Comment by duck-rh** [comment]
Interestingly the recommendation from github devs differ: https://github.com/blog/967-github-secrets
« But did you know you can use Pull Requests between branches, on the same repository? You don't need to fork repositories to use Pull Requests. Internally at GitHub, we almost always use Pull Requests between branches. »

**Comment by thatdocslady** [comment]
@duck-rh as the saying goes "just because you can, doesn't mean you should", and especially for maintainers the forking recommendation is meant as an extra precaution in case someone forgets to create a new branch and might accidentally merge directly into master. Better safe than sorry in this case.

**Comment by duck-rh** [comment]
True, but you forgot the nice new feature Garrett found recently, which disallow pushing directly into master.

Whatever the outcome, the said feature has already be enabled on this repo, announced on the ML, and no one complained. I think we should think about making this a default config (and explain why in the doc if necessary).

**Pull request merged**
