### PR TITLE
Added 102816 blog

### PR DESCRIPTION
**Pull request by bproffitt**
Changes proposed in this pull request:
- New blog highlighting the new code of conduct
## 
## 

I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @bproffitt

### CODE REVIEW

**Comment by bproffitt** [comment]
@mscherer @duck-rh @garrett Can one of you take a look and tell me why this is failing the tests? My local middleman instance is failing too, so I don't know if that's an issue. But this is a straightforward blog entry so I don't know why it is failing. Thanks!

**Comment by duck-rh** [comment]
The error is in the index page, looking into it.

**Comment by bproffitt** [comment]
I may have figured this out; there was no readmore. Totally my error.

**Comment by duck-rh** [comment]
I just found out READMORE was a special keyword (blog.summary_separator) and I remember bothering you about structuring pages in another PR, sorry about that.

Nevertheless, there is no obligation to have one according to the middleman-blog code, so I will maintain my PR and discuss this with @garrett.

**Comment by garrett** [comment]
`READMORE` is optional; it isn't needed, unless you want to break an article for a summary at a specific point.

**Pull request merged**
