### PR TITLE
Add engine API explorer

### PR DESCRIPTION
**Pull request by jhernand**
This patch adds the HTML and JavaScript code of the engine API explorer
application, and the JSON file containing the description of version
4.0.20 of the API specification. The application should be available in
the following URL:

  http://www.ovirt.org/documentation/api-explorer

That should be identical to what is currently available here:

  https://jhernand.fedorapeople.org/ovirt-api-explorer

Note that the "index.js" file isn't the original source code of the
application, but the result of running "webpack" to pack together all
the JavaScript source code. The original source code is available in the
"ovirt-engine-api-explorer" project hosted in "gerrit.ovirt.org".

The "model.json" has also been automatically generated from the API
model available in the "ovirt-engine-api-model" project, version 4.0.20.

Signed-off-by: Juan Hernandez <juan.hernandez@redhat.com>

### CODE REVIEW

**Comment by thatdocslady** [comment]
@sandrobonazzola can you help with this? it seems like the PR is misplaced..

**Comment by jhernand** [comment]
Note that I think that placing this code in this repository is not the best thing. I'd prefer to have a space in ovirt.org where this application can be uploaded, maybe automatically, from an Jenkins job.

In addition this pull request is out of date, please don't merge it.

**Comment by sandrobonazzola** [comment]
:-1:  as per @jhernand comment. Juan, do you want to update this or may I close the PR?

**Comment by jhernand** [comment]
Close it, please.

**Comment by bproffitt** [comment]
Closed, per request.

**Pull request closed without merging**
