### PR TITLE
RHV-42139.0 Sync downstream (RHV) doc repo changes to upstream (oVIrt)

### PR DESCRIPTION
**Pull request by stoobie**
Syncing downstream (RHV) documentation changes to upstream (oVIrt).

Before merging this, I need to know if there are any documentation PRs from oVirt that have not been synced with the downstream.

We also need to build every document and confirm it builds without errors.

Changes proposed in this pull request:

See list of commit messages.

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @stoobie 

This pull request needs review by: @sandrobonazzola, @duck-rh

### CODE REVIEW

**Comment by emarcusRH** [comment]
@stoobie it looks like some of the conflicting files in the Admin Guide upstream that I previously mentioned are being deleted in this PR from Aviv Litman- https://github.com/oVirt/ovirt-site/pull/2543

**Comment by stoobie** [comment]
@sandrobonazzola @duck-rh This PR is ready for review. I have added all downstream changes. Let me know if you see any issues. Note that I have _not_ generated a preview of ovirt-site to test it. I sometimes have issues with generating a preview.

**Comment by sandrobonazzola** [comment]
There are a few broken links:
```
- ./_site/documentation/administration_guide/assembly-enabling-encrypted-vnc-consoles-for-fips.html
  *  internally linking to {URL_customer-portal}downloads/content/415/ver=4.3/rhel---7/4.3/x86_64/product-software, which does not exist (line 248)
     <a href="{URL_customer-portal}downloads/content/415/ver=4.3/rhel---7/4.3/x86_64/product-software">Installers and Images for Red Hat Virtualization Manager (v. 4.3 for x86_64)</a>
  *  internally linking to {URL_customer-portal}solutions/1168383, which does not exist (line 306)
     <a href="{URL_customer-portal}solutions/1168383">Google Chrome</a>
  *  internally linking to {URL_customer-portal}solutions/17864, which does not exist (line 303)
     <a href="{URL_customer-portal}solutions/17864">Internet Explorer</a>
  *  internally linking to {URL_customer-portal}solutions/95103, which does not exist (line 300)
     <a href="{URL_customer-portal}solutions/95103">Firefox</a>
- ./_site/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_cockpit_web_interface/index.html
  *  internally linking to URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance, which does not exist (line 2751)
     <a href="URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance">Available disk schedulers</a>
- ./_site/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_cockpit_web_interface/master.html
  *  internally linking to URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance, which does not exist (line 3019)
     <a href="URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance">Available disk schedulers</a>
- ./_site/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/index.html
  *  internally linking to URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance, which does not exist (line 2825)
     <a href="URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance">Available disk schedulers</a>
- ./_site/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/master.html
  *  internally linking to URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance, which does not exist (line 3096)
     <a href="URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance">Available disk schedulers</a>
- ./_site/documentation/introduction_to_the_vm_portal/index.html
  *  internal image 1.png does not exist (line 378)
  *  internal image 2.png does not exist (line 410)
  *  internal image 3.png does not exist (line 416)
  *  internal image Console.png does not exist (line 438)
  *  internal image Edit_VM.png does not exist (line 577)
  *  internal image Edit_VM.png does not exist (line 641)
  *  internal image Edit_VM.png does not exist (line 655)
  *  internal image Edit_VM.png does not exist (line 669)
  *  internal image Run.png does not exist (line 435)
  *  internal image VM_screen.png does not exist (line 370)
```

**Comment by stoobie** [comment]
> @stoobie it looks like some of the conflicting files in the Admin Guide upstream that I previously mentioned are being deleted in this PR from Aviv Litman- #2543

@emarcusRH I rebased this PR, so those changes are now present.

**Comment by stoobie** [comment]
> There are a few broken links:
> 
> ```
> - ./_site/documentation/administration_guide/assembly-enabling-encrypted-vnc-consoles-for-fips.html
>   *  internally linking to {URL_customer-portal}downloads/content/415/ver=4.3/rhel---7/4.3/x86_64/product-software, which does not exist (line 248)
>      <a href="{URL_customer-portal}downloads/content/415/ver=4.3/rhel---7/4.3/x86_64/product-software">Installers and Images for Red Hat Virtualization Manager (v. 4.3 for x86_64)</a>
>   *  internally linking to {URL_customer-portal}solutions/1168383, which does not exist (line 306)
>      <a href="{URL_customer-portal}solutions/1168383">Google Chrome</a>
>   *  internally linking to {URL_customer-portal}solutions/17864, which does not exist (line 303)
>      <a href="{URL_customer-portal}solutions/17864">Internet Explorer</a>
>   *  internally linking to {URL_customer-portal}solutions/95103, which does not exist (line 300)
>      <a href="{URL_customer-portal}solutions/95103">Firefox</a>
> - ./_site/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_cockpit_web_interface/index.html
>   *  internally linking to URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance, which does not exist (line 2751)
>      <a href="URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance">Available disk schedulers</a>
> - ./_site/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_cockpit_web_interface/master.html
>   *  internally linking to URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance, which does not exist (line 3019)
>      <a href="URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance">Available disk schedulers</a>
> - ./_site/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/index.html
>   *  internally linking to URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance, which does not exist (line 2825)
>      <a href="URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance">Available disk schedulers</a>
> - ./_site/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/master.html
>   *  internally linking to URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance, which does not exist (line 3096)
>      <a href="URL_rhel_docs_latest/html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance">Available disk schedulers</a>
> - ./_site/documentation/introduction_to_the_vm_portal/index.html
>   *  internal image 1.png does not exist (line 378)
>   *  internal image 2.png does not exist (line 410)
>   *  internal image 3.png does not exist (line 416)
>   *  internal image Console.png does not exist (line 438)
>   *  internal image Edit_VM.png does not exist (line 577)
>   *  internal image Edit_VM.png does not exist (line 641)
>   *  internal image Edit_VM.png does not exist (line 655)
>   *  internal image Edit_VM.png does not exist (line 669)
>   *  internal image Run.png does not exist (line 435)
>   *  internal image VM_screen.png does not exist (line 370)
> ```

@sandrobonazzola I fixed all the errors.

**Review by sandrobonazzola — APPROVED** [review]

**Pull request merged**
