### PR TITLE
Add the Feature Page for the Max Free Memory Tooltip

### PR DESCRIPTION
**Pull request by pcbailey**
Changes proposed in this pull request:
- Add a feature page for RFE [1], which adds an explanatory tooltip to the "Max Free Memory for scheduling VMs" field in the "General" sub tab of the "Hosts" main tab of the webadmin UI.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1288990

I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @pcbailey

This pull request needs review by: (please @mention the reviewer if relevant)

Adds a feature page for RFE [1], which adds an explanatory tooltip to
the "Max Free Memory for scheduling new VMs" field in the "General" sub
tab of the "Hosts" main tab in the webadmin UI.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1288990

### CODE REVIEW

**Comment by pcbailey** [comment]
This is a draft page. The feature is not yet finalized and may still change.

**Comment by doron-fediuck** [comment]
It's a good start but there's still more work to be done on the design.
Let's have a more 'baked' version before merging this.

**Comment by sandrobonazzola** [comment]
Is this still relevant?

**Comment by gregsheremeta** [comment]
> Is this still relevant?

oh i don't think we need to be doing feature pages for tooltips

**Pull request closed without merging**
