### PR TITLE
Add ovirt-img presentation

### PR DESCRIPTION
**Pull request by nirs**
Was presented in RHV Demo, which is not really a conference but the content is useful to the community.

Signed-off-by: Nir Soffer <nsoffer@redhat.com>

### CODE REVIEW

**Review by aesteve-rh — APPROVED** [review]

**Review by ahadas — COMMENTED** [review]
@nirs can we easily change `Secret Plan` to `"Secret" Plan`?

**Comment by nirs** [comment]
@ahadas sure

**Comment by nirs** [comment]
Sending another version to fix capitalization and rebase.

**Review by sandrobonazzola — APPROVED** [review]
Merging based on given approval

**Pull request merged**
