### PR TITLE
Update recommended browsers

### PR DESCRIPTION
**Pull request by gregsheremeta**
Update recommended browsers to remove Chrome, add "ESR" to Firefox.

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
+1

**Comment by mykaul** [comment]
@gregsheremeta  - why did we decide to remove Chrome? Is it much worse than Firefox? Since we cannot recommend a version?

Do we want to provide a link to ESR (https://www.mozilla.org/en-US/firefox/organizations/) page?

**Comment by gregsheremeta** [comment]
@mykaul Chrome has never been officially supported. We're fixing a BZ by removing its mention.

Re: providing a link to ESR, that's fine with me but would be up to Oved or Yaniv Dary or you.

**Comment by mykaul** [comment]
@gregsheremeta  - I'd add the link to what ESR is - not many know.

**Pull request merged**
