### PR TITLE
Home page redesigned and refreshed

### PR DESCRIPTION
**Pull request by eldan**
Hi,
In the following branch changes, I made an overall graphic change for the home page.
It is more appealing (added graphic elements and colors)
The sections are much more clear.
Case studies section shows 3 last added cases.
Attached is a screenshot of the result.
ovirt_hp

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): 
Thanks,
@eldan

This pull request needs review by: (please @mykaul @doron-fediuck  @sandrobonazzola  the reviewer if relevant)

### CODE REVIEW

**Comment by doron-fediuck** [comment]
Looks good to me. Waiting for others to take a look.

**Comment by duck-rh** [comment]
Looks better indeed. Nevertheless the "getting started" links are all gone, no mention of the latest release; are people going to find their way in the documentation? Also there's no link to the events now, and as it's not in the menu either, I see no way to reach them; maybe add a link in the "community is key" section and/or the menu.

**Comment by mureinik** [comment]
Nitpicking: The "What is oVirt" paragraph has an opening `(` without a closing `)`

Other than that, looks great

**Comment by rollandf** [comment]
Looks great.
Maybe add a link to the events page in the community section as suggested by duck.

**Comment by doron-fediuck** [comment]
@duck-rh @mureinik @rollandf any further comments before merge?

**Comment by rollandf** [comment]
👍

**Comment by rgolangh** [comment]
The twitter feed and the picture on the right are not levelled

**Comment by sandrobonazzola** [comment]
:+1:

**Pull request merged**
