### PR TITLE
Add vinchin as one of backup providers

### PR DESCRIPTION
**Pull request by ZhangjuanLee**
Fixes issue # (delete if not relevant)

Changes proposed in this pull request:

-logos: add vinchin.png

-users-and-providers: add vinchin in backup provider section

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @ZhangjuanLee to sign)

This pull request needs review by: (please @sandrobonazzola  the reviewer if relevant)

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
@shallao can you please review?

@doron-fediuck @mtessun can you please review?

**Comment by shallao** [comment]
@sandrobonazzola I confirm it is correct from our point of view. Could you please approve it if no problem from your side as well? Thanks Sandro!

**Comment by doron-fediuck** [comment]
LGTM

**Comment by mtessun** [comment]
LGTM as well

**Pull request merged**
