### PR TITLE
Remove status colors from feature list

### PR DESCRIPTION
**Pull request by JohnMarksRH**
## Fixes issue
Status colors on [feature page ](https://www.ovirt.org/develop/release-management/features/) make the page hard on the eyes and the color codes don't really add value as the viewer wouldn't necessarily know what they represent

## Changes proposed in this pull request:

- Remove status color coding so that all links will be in green - like elsewhere on site

- Bold green for selected feature remains unchanged 

I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @jmarks

This pull request needs review by: @mykaul @duck-rh

### CODE REVIEW

**Comment by JohnMarksRH** [comment]
@duck-rh @mykaul changes requested by @duck-rh implemented. Hover over status remains. Colors removed.

**Comment by duck-rh** [comment]
you implemented only a small part of the cleanup. if we leave as is, then in a few days we'll have totally forgotten about this and it will be much more complicated to understand and clean.

**Comment by JohnMarksRH** [comment]
@duck-rh How about a short blue jeans meeting and you can explain to me what else to delete so we can get this small task sorted. OK?

**Comment by duck-rh** [comment]
So I push a new commit to cleanup quite some useless code. For example the status selection checkboxes did not work and was useless, and then all the statuses computation was removed as well. I did not squash so you can see my changes separatly very easily. I also rebased on master so you need to refetch your branch.

You stated in this PR that "Bold green for selected feature remains unchanged" so I guess you wish this to stay. Honestly I think this is not very important. Anyway your commit "remove colors from feature page" broke this feature. In this case you just need to remove the status part of the classes, not the wholes classes itself as it is used to activate the bold green color. I can make the changes for you, or you can take over the branch again, as you prefer.

So this is almost done and once the last question is replied we can ﬁnish the last piece of the patches, squash, and test the result before merging.

**Comment by duck-rh** [comment]
Kept the bold green color feature as requested.

So I removed your second commit and integrated the changes on the classes in my own commit.

It seems to work well but please test carefully for regressions before merging.

**Comment by JohnMarksRH** [comment]
@duck-rh Thanks! Everything is working. Merged.

**Pull request merged**
