### PR TITLE
oVirt was not accepted for GSoC 2018. Removed ideas and added a note.

### PR DESCRIPTION
**Pull request by gregsheremeta**
Changes proposed in this pull request:
oVirt was not accepted for GSoC 2018. Removed ideas and added a note.

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @gregsheremeta

This pull request needs review by: @jelkosz @mykaul @sandrobonazzola

### CODE REVIEW

**Comment by mykaul** [comment]
The ideas are still good and can be used for Outreachy or any other volunteer or for 2019 - why remove them?

**Comment by jelkosz** [comment]
hmmm, maybe makes sense to keep them there for inspiration... We could have a note above them that even though we don't participate in GSoC, if someone wants to contribute this in his free time, we would be happy to provide the guidance.

**Comment by gregsheremeta** [comment]
I just left it at "previous ideas"

good?

**Comment by jelkosz** [comment]
yep, sounds good

**Pull request merged**
