### PR TITLE
update to up and running with ovirt and gluster storage howto

### PR DESCRIPTION
**Pull request by jasonbrooks**
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @jasonbrooks

This pull request needs review by: (please @mention the reviewer if relevant)

### CODE REVIEW

**Comment by dpmramesh** [comment]
We have improved the hyperconverged deployment in oVirt 4.1 using gdeploy wizard in Cockpit. This will help you to avoid manually editing any gdeploy config file or hosted-engine answer file. Everything will be done through Cockpit UI. Also Gluster and gdeploy ( gdeploy will be included in 4.1.1 if not in 4.1.0) is packaged into oVirt Node in 4.1. I think its worth to include these feature in this blog post. I can help you with more details if required.

**Comment by jasonbrooks** [comment]
OK, I'll check it out and modify the post, and ping you with any questions.
Thanks!

**Comment by tiraboschi** [comment]
hi Jason, probably at the same time I was writing a similar post: https://github.com/oVirt/ovirt-site/pull/803
I had a few screenshots there of the new cockpit plugin.

**Comment by jasonbrooks** [comment]
@dpmramesh gdeploy isn't in the current node image, but I think I can get it working. Do you know when 4.1.1 will be available?

@tiraboschi If my post is too redundant w/ yours, I can just put it on my own blog or elsewhere

**Comment by jasonbrooks** [comment]
@dpmramesh I got it working -- At this point, I don't know if this is actually easier/better through cockpit than it is through ssh. You may not have to edit a gdeploy file, but you have to edit the fields in the web app, and the hosted-engine setup part of the app is pretty much identical to what you do over the console. I do like using the node and having the cockpit interface available. One thing that annoyed me about the gdeploy web app bit was how, if something went wrong, you couldn't just re-run gdeploy. You have to cancel out and fill out the whole wizard again. When I'm running gdeploy in the console, and something goes wrong, I can re-run straight away.

It would be awesome if the gdeploy wizard could step you through configuring your storage using what cockpit can display / configure about storage.

**Comment by dpmramesh** [comment]
@jasonbrooks One big advantage is Cockpit plugin is, user need not edit the config file manually. If gdeploy is packaged into Node (in 4.1.1),  he need not worry about  gdeploy or its config file at all. With cockpit-gdeploy wizard, user has to edit very few information which is specific to his system. We felt it is easy to enter details in UI then editing the file for the first time users. Also oVirt recommends  hosted-engine setup through UI rather than console. They are planning to improve the UI experience in oVirt 4.2. 

Another important thing, you need not worry about passing correct gluster volume details and mount options to hosted-engine setup. When you continue to hosted-engine setup from gdeploy wizard, it automatically configures gluster as the storage domain and passe the gluster volume with proper mount options. These questions will not be asked again in hosted-engine setup. Also we have pre filled most of the default answer for hyperconverged setup. 

 Regarding re-deploy, We have a bug to track the support for re-deploy. It will be fixed in ovirt 4.1.1. 

>>It would be awesome if the gdeploy wizard could step you through configuring your storage using what cockpit can display / configure about storage.
This is little difficult for now. We need to configure storage in three different nodes not just the first node. Also gdeploy has the all logic to configure the storage as per gluster requirements for better performance. If we configure storage using cockpit then we may have to replicate the whole logic again.

Note: With oVirt 4.1.1 I think many things will improve. We will have preflight checks from gdeploy. We have added more validations and more notes for the users to enter correct value. We are trying to avoid editing the config file as much as possible. May be you can visit to http://red.ht/2kThEnv to see what is coming in oVirt 4.1.1. 

Regarding oVirt 4.1.1 availability we already have second test build. May be @sandrobonazzola  knows exact timeline. 

http://www.ovirt.org/release/4.1.1/

**Comment by jasonbrooks** [comment]
OK, I'll test with the 4.1.1 content.

**Comment by jasonbrooks** [comment]
@dpmramesh OK, I've modified it to use oVirt Node and the cockpit stuff. I couldn't figure out how to test the node w/ 4.1.1 content. There's a master node image, but that looks like itis tracking 4.2. I tried yum updating the node, and got a bunch of new packages, but the cockpit plugin wasn't working. I figure we can pub this now, and then I can make an update or two where relevant when 4.1.1 comes out.

**Comment by piotr-gbyliczek** [comment]
Just followed the post to build ovirt lab, and ended up with data storage domain that is 19GB :) 

The post mentions editing [lv2], which is the thin pool, but not the [lv3], which is actually the lvm volume for the data storage domain. 

I think the post could benefit from making this clear, maybe adding a sentence to explain that it does create thin pool and then volumes in it ? 

All of this is easily fixed, one can expand the data volume and filesystem on it, once it is done on all gluster hosts,  ovirt can pick it up and show the new space (had to do it manually by syncing bricks per host, not sure if there is any automated process to do it.)

**Comment by dpmramesh** [comment]
@piotr-gbyliczek You don't need to sync the bricks. Gluster volume capacity information will be synced automatically within 5 minutes. Also I think capacity of the storage domain is synced immediately. So user just needs to expand the LV and XFS if he needs to expand the brick size.

**Comment by mykaul** [comment]
@jasonbrooks - can you resolve the conflicts so we can go ahead with this PR?

**Comment by jasonbrooks** [comment]
I messed this up trying to fix the conflict. I replaced with #877

**Pull request closed without merging**
