### PR TITLE
Fix user story issue in home page

### PR DESCRIPTION
**Pull request by rollandf**
Fixes issue #1000 

Changes proposed in this pull request:

- Removed empty section in users-stories.html.md

- Moved Florida State University to the end of the file in order to be seen in the home page

- Fix comment in index,html about where the user stories are located

I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @rollandf

This pull request needs review by: @JohnMarksRH @duck-rh

### CODE REVIEW

**Comment by duck-rh** [comment]
The changes are fine.

I think we should add a comment in _users-stories.html.md_ to explain which case is gonna be on the front page.

Also I wonder why the **last** one is selected. On the case study page this is the last, so the least visible, so it seems illogical. I would imagine the most important and recent ones to be one the top of the page, and the old ones to go down with time and at some point disappear. If people agree I think it is trivial to change the logic of the selection and I could help.

**Comment by JohnMarksRH** [comment]
@rollandf @duck-rh Looks good and Duck's suggestion makes sense.

**Comment by rollandf** [comment]
@duck-rh I fix according to your comment.
It makes much more sense now.

**Comment by duck-rh** [comment]
works nicely, thanks :-)

**Comment by JohnMarksRH** [comment]
Great!

**Pull request merged**
