### PR TITLE
oVirt 4.5.0 Release

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Fixes issues #2797 #2764 #2838

Changes proposed in this pull request:

- Update the website to reflect oVirt 4.5.0 GA

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sandrobonazzola 

This pull request needs review by: @oVirt/developers @oVirt/ovirt-documentation

### CODE REVIEW

**Review by sanjacodes — APPROVED** [review]
LGTM, maybe someone else as well for a final review?

**Comment by sandrobonazzola** [comment]
> LGTM, maybe someone else as well for a final review?

Sure! GA is planned on April 20th so there's time for many more reviews and suggestions

**Review by dcdacosta — APPROVED** [review]
/lgtm

**Review by dcdacosta — APPROVED** [review]
/lgtm

**Pull request merged**
