### PR TITLE
2016-06-18-ovirt-engine-4_0-setup-in-fedora24.html.md

### PR DESCRIPTION
**Pull request by yanirq**
Signed-off-by: yquinn <yquinn@redhat.com>

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
Why a blog post instead of a feature page for introducing support for fedora 24? See http://www.ovirt.org/develop/release-management/features/engine/fedora-22-support/

**Comment by mykaul** [comment]
@sandrobonazzola Blog has more visibility, no? And it's good timing, along with F24 release.

**Comment by yanirq** [comment]
This blog post is intended for introducing ongoing possible issues and
solutions when installing ovirt engine on fedora 24 for the near future.
A summary blog of issues & solutions if we want to look at it that way.
Later on I presume we can introduce a page for supporting fedora 24 (which
can relay on this blog post among other reports from the community)

Regards,
Yanir Quinn

**Comment by yanirq** [comment]
@sandrobonazzola  Can we merge this pull request ?

**Comment by bproffitt** [comment]
Since this is a blog, I will merge. Working on it now.

**Pull request merged**
