### PR TITLE
[wip draft] new template for release page

### PR DESCRIPTION
**Pull request by gregsheremeta**
new template for release page
 - use Open Sans font
 - update language to be more consistent with home and download pages
 - remove installation and upgrade text, since it just duplicates
   what should be elsewhere

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @gregsheremeta 

This pull request needs review by: @sandrobonazzola

### CODE REVIEW

**Comment by gregsheremeta** [comment]
old:
old

**Comment by gregsheremeta** [comment]
new:
new

**Comment by gregsheremeta** [comment]
hi @sandrobonazzola , lmk what you think. First pass at some language tweaks. Changed the font to Open Sans too.

**Comment by sandrobonazzola** [comment]
looks good to me in general, but the template is in releng-tools project :-)

**Comment by sandrobonazzola** [comment]
Closing this PR, pushed https://gerrit.ovirt.org/#/c/102762/ to continue the review.

**Pull request closed without merging**
