### PR TITLE
Update TPM feature page according to the feature implementation

### PR DESCRIPTION
**Pull request by mz-pdm**
Changes proposed in this pull request:

- The feature page updated in accordance to the current implementation.

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @mz-pdm 
This pull request needs review by: @ahadas

### CODE REVIEW

**Comment by mz-pdm** [comment]
@ahadas ping

**Comment by sandrobonazzola** [comment]
@mz-pdm can you please rebase and address the issues reported by CI?

**Comment by mz-pdm** [comment]
Rebased (the previous CI problem was just a system error).

**Review by sandrobonazzola — APPROVED** [review]
LGTM, but waiting for @ahadas to review as well

**Review by ahadas — APPROVED** [review]

**Pull request merged**
