### PR TITLE
added how-to for enabling usb2 on linux vms

### PR DESCRIPTION
**Pull request by jwoytek**
Changes proposed in this pull request:

- add file enable-usb2-linux-vm.html.md in how-tos. 

I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (please @mention yourself to sign) @jwoytek

This pull request needs review by: (please @mention the reviewer if relevant)

### CODE REVIEW

**Comment by jwoytek** [comment]
This is my first contribution to the documents repo, so please let me know if there are any protocols I missed or style I didn't follow, and I'll fix whatever I need to fix.

**Comment by mykaul** [comment]
@michalskrivanek - can someone review this?

**Comment by michalskrivanek** [comment]
LGTM

@jwoytek, you can perhaps also note that on ppc64le the default is nec-xhci since there is no SPICE nor smartcard support so we could change the default

**Comment by jwoytek** [comment]
@michalskrivanek I will make an update to that effect shortly. Thanks!

**Pull request merged**
