### PR TITLE
Fix up multiple storage domains page

### PR DESCRIPTION
**Pull request by mureinik**
Issues handled:
- Fixed title
- Updated the version this feature was included in
- Fixed formatting issues
- Fixed images display

### CODE REVIEW

**Comment by mureinik** [comment]
@JohnMarksRH / @danielerez / @rollandf can you please review?

**Comment by rollandf** [comment]
👍

**Comment by mureinik** [comment]
@rollandf sorry, just noticed now that some changes are missing. Can you re-review, please?

**Comment by danielerez** [comment]
Looks good

**Comment by JohnMarksRH** [comment]
@mureinik It's fine with me :)

**Comment by mureinik** [comment]
> The English looks fine but the structure and purpose of the doc is not clear.
This is a traditional feature page from the old wiki. 
Let's merge this patch for improving on the layout/location of files, and if we decide we want to put more effort in to updating old 3.1 feature pages we can do so later.

**Pull request merged**
