### PR TITLE
Snapshots overview

### PR DESCRIPTION
**Pull request by mureinik**
Changes proposed in this pull request:
- Improve Snapshots Overview page grammar and phrasing
- Improve/fix Snapshots Overview styling and formatting damaged by the migration from mediawiki to middleman
- Add bugzilla references to Snapshots Overview

I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @mureinik

This pull request needs review by: @danielerez

### CODE REVIEW

**Comment by danielerez** [comment]
Code change looks good.
Not sure about the CI failure.

**Comment by duck-rh** [comment]
you removed the title in the headers, don't know why, but this is compulsory.

**Comment by mureinik** [comment]
@garrett Yes, indeed, that was a dumb mistake (probably a `dd` slip in vi. Maybe it's time I get a growup's editor `-)). Thanks!

**Comment by mureinik** [comment]
Let's wait for the CI to finish to verify this claim, though.

**Pull request merged**
