### PR TITLE
Improvements to the Actions-Permissions Overview page

### PR DESCRIPTION
**Pull request by mureinik**
Fixing issues in the Action Permissions Overview page

### CODE REVIEW

**Comment by mureinik** [comment]
@oourfali Can someone from your team review this PR please? Not sure who's in charge of this nowadays.

**Comment by oourfali** [comment]
@mwperina can you take a look?

**Comment by mureinik** [comment]
@mwperina ping?

**Comment by mwperina** [comment]
Patches, looks good to me. Who have privileges to merge them?

**Comment by mureinik** [comment]
AFAIK @mykaul / @sandrobonazzola / @thatdocslady

**Pull request merged**
