### PR TITLE
Create hosted-engine-migration-to-4-0.md

### PR DESCRIPTION
**Pull request by tiraboschi**
Adding a new feature page for the hosted-engine upgrade tool

### CODE REVIEW

**Comment by tiraboschi** [comment]
@rgolangh @sandrobonazzola @rafaelmartins can you please take a look?

**Comment by rafaelmartins** [comment]
something is broken in travis build: https://travis-ci.org/oVirt/ovirt-site/builds/138385188

**Comment by tiraboschi** [comment]
The issue seams on another page:
       error  build/develop/release-management/features/hosted-engine-vm-management/index.html
undefined method `title' for nil:NilClass

**Comment by rafaelmartins** [comment]
yeah, but master is passing, and the failure is in the same directory of the file you added. the static website generator is probably doing something weird.

I tested it locally and the new page is not rendering. :(

**Comment by duck-rh** [comment]
Quack,

On 06/18/2016 12:47 AM, Rafael Martins wrote:
> yeah, but master is passing, and the failure is in the same directory of
> the file you added. the static website generator is probably doing
> something weird.

I wonder if the two dots in the name are not a problem. I think we
encountered such kind of weird behavior. So could you try to build with
the filename s/4\.0/4_0/ for example?

If not I will have a deeper look next week.

\_o<

**Comment by thatdocslady** [comment]
@duck-rh @jasonbrooks can you assist here please?

**Comment by sandrobonazzola** [comment]
@tiraboschi can you rename using 4_0 instead of 4.0 ?

**Comment by rafaelmartins** [comment]
:+1:

**Comment by sandrobonazzola** [comment]
:+1:

**Pull request merged**
