### PR TITLE
Update feature-template.html.md

### PR DESCRIPTION
**Pull request by Adam-Weiss**
Changes proposed in this pull request:
some changes were made to improve on the consistency of the instructions given in the template and redundant words were removed. please excuse any work-flow errors on my part just this time.
-

-

-

I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (please @mention yourself to sign)

This pull request needs review by: @mykaul @doron-fediuck @dyaniv @JohnMarksRH

### CODE REVIEW

**Comment by JohnMarksRH** [comment]
@sandrobonazzola @mykaul @doron-fediuck This merged version contains spelling errors / typos, and grammar issues that detract from clarity. The link at the top of the page has not been entered correctly. There are also structure / headings issues. For example, the opening sentence, "the actual name of your feature.." belongs under the heading "Your Feature Name". This is an important page. Therefore, I suggest a new PR with a revised version.

**Comment by dyaniv** [comment]
How did this overwrite the changes I proposed? Why where they not integrated into this?

**Comment by JohnMarksRH** [comment]
@dyaniv @sandrobonazzola 
As I explained previously, the changes we discussed were implemented in this PR
https://github.com/oVirt/ovirt-site/pull/979
I mistakenly closed it.

**Comment by dyaniv** [comment]
So please reopen or resubmit the changes

**Comment by JohnMarksRH** [comment]
@dyaniv @sandrobonazzola @mykaul 
There doesn't seem to be an option to reopen that PR. Suggest we agree **together** how to tackle the changes so there are no confusions.

**Pull request merged**
