### PR TITLE
changing f* to fc* - typo fix

### PR DESCRIPTION
**Pull request by bronhaim**
Fixes type: changes proposed in this pull request:
- changing f* to fc* in link url
Yaniv Bronhaim <bronhaim@gmail.com>

### CODE REVIEW

**Comment by mureinik** [comment]
@bronhaim please sign the PR as per the template, thanks!

**Comment by rollandf** [comment]
@bronhaim Can you address Allon's comment ?

**Comment by bronhaim** [comment]
@rollandf I don't know what does pull request per template mean .. I wish I would.

**Comment by mureinik** [comment]
There's a standard template for pull request messages (as, e.g., seen at the top of this page). There are places that you need to fill in (e.g., signing your name, removing the issue # since this PR does not solve an open issue, etc.). Could you please do so?

**Comment by bronhaim** [comment]
@mureinik Done

**Pull request merged**
