### PR TITLE
Code block fixes

### LINKED ISSUE #21: Wrongly rendered quotes (seen in in a cople pages iirc)
one of them http://beta-ovirtweb.rhcloud.com/develop/infra/infra-bash-style-guide/

### PR DESCRIPTION
**Pull request by garrett**
When merged, this should fix #21.

### CODE REVIEW

**Comment by garrett** [comment]
These additional pages may need to be fixed:

* community/get-involved/wiki-rules-and-etiquette.html.md
* develop/developer-guide/vdsm/hook/vmfex.html.md
* develop/dev-process/working-with-gerrit.html.md
* develop/infra/phoenix-lab-hosts.html.md
* develop/infra/phoenix-lab-ssh-spice-tunnel.html.md
* develop/infra/phoenix-lab-storage-hosts.html.md
* develop/infra/proxy.html.md
* develop/release-management/features/storage/cinder-integration.html.md
* develop/release-management/features/ux/detailedhostpmmultipleagents.html.md
* documentation/admin-guide/administration-guide.html.md

Please add the fixes in this (soon to be improperly titled) branch (`bash-infra-fixups`).

**Comment by thatdocslady** [comment]
@garrett how difficult/time-consuming/annoying would it be to fix the quotes in the list of files that you mentioned? Is it a find-and-replace thing or manual labor?

**Comment by garrett** [comment]
@thatdocslady: It probably depends on the usage in the files in question. I can probably fix most of the quoting rather easily... I'm not sure about the block quoting. I guess a good first step would be to work on a quick fix for the quoting.

The problem stems from these facts:

1. there is no perfect way to translate MediaWiki source to Markdown
2. a considerable amount of source material in MediaWiki was actually even broken in MediaWiki

For item 2, that bit us in many other ways across the site. There are some issues currently open within the infra section thanks to the excellent @david-caro due to this — and I'm sure there are other pages that we haven't seen yet bitten by this problem (semi-broken source material resulting in semi-broken converted documents).

As there's simply so much documentation of oVirt, there are probably more conversion issues too. Again, however, I think _most_, but not all, of the issues are related to point 2. The quoting, I believe, is more of a conversion problem. In the case of quoting, that should be easy-ish to detect (which I did above with a grep) and fix.

**Comment by garrett** [comment]
Okay, I've found and fixed a bunch of improper quoting in git commit d382cbe. This doesn't necessarily fix or optimize the codeblocks however (but it shouldn't hurt at least).

If a codeblock is broken, then the spacing in front would matter, or it could be better fixed by using fenced triple backticks. If using the triple backticks, then the starter set can optionally set the language — doing so would provide syntax highlighting. If using the fenced triple backtics, it's best to change the indentation level to start flush with the left side, so there wouldn't be extra space to the left of the codeblock when rendered on the page. Most code editors can handle block unindenting; otherwise just trimming a few spaces to the left of each line works too (if using fenced code block indications, like the triple backticks).

**Comment by garrett** [comment]
Here's a list of the changed files, to help see the errors on the website, in case codeblocks _need_ fixing (or optimizing, like one indented block should be two blocks via fencing, etc.):

* [/admin-guide/administration-guide/](https://beta-ovirtweb.rhcloud.com/admin-guide/administration-guide/)
* [/developer-guide/vdsm/hook/vmfex/](https://beta-ovirtweb.rhcloud.com/developer-guide/vdsm/hook/vmfex/)
* [/develop/infra/infra-bash-style-guide/](https://beta-ovirtweb.rhcloud.com/develop/infra/infra-bash-style-guide/)
* [/develop/infra/phoenix-lab-hosts/](https://beta-ovirtweb.rhcloud.com/develop/infra/phoenix-lab-hosts/)
* [/develop/infra/proxy/](https://beta-ovirtweb.rhcloud.com/develop/infra/proxy/)
* [/dev-process/working-with-gerrit/](https://beta-ovirtweb.rhcloud.com/dev-process/working-with-gerrit/)
* [/features/storage/cinder-integration/](https://beta-ovirtweb.rhcloud.com/features/storage/cinder-integration/)
* [/get-involved/wiki-rules-and-etiquette/](https://beta-ovirtweb.rhcloud.com/get-involved/wiki-rules-and-etiquette/)
* [/infra/phoenix-lab-ssh-spice-tunnel/](https://beta-ovirtweb.rhcloud.com/infra/phoenix-lab-ssh-spice-tunnel/)
* [/infra/phoenix-lab-storage-hosts/](https://beta-ovirtweb.rhcloud.com/infra/phoenix-lab-storage-hosts/)
* [/releases/3.3.2/testing/](https://beta-ovirtweb.rhcloud.com/releases/3.3.2/testing/)
* [/ux/detailedhostpmmultipleagents/](https://beta-ovirtweb.rhcloud.com/ux/detailedhostpmmultipleagents/)

**Comment by garrett** [comment]
Here's the same list, but pointed at local pages, for local development:

* [/community/get-involved/wiki-rules-and-etiquette/](http://0.0.0.0:4567/community/get-involved/wiki-rules-and-etiquette/)
* [/develop/developer-guide/vdsm/hook/vmfex/](http://0.0.0.0:4567/develop/developer-guide/vdsm/hook/vmfex/)
* [/develop/develop/infra/proxy/](http://0.0.0.0:4567/develop/infra/proxy/)
* [/develop/dev-process/working-with-gerrit/](http://0.0.0.0:4567/develop/dev-process/working-with-gerrit/)
* [/develop/infra/infra-bash-style-guide/](http://0.0.0.0:4567/develop/infra/infra-bash-style-guide/)
* [/develop/infra/phoenix-lab-hosts/](http://0.0.0.0:4567/develop/infra/phoenix-lab-hosts/)
* [/develop/infra/phoenix-lab-ssh-spice-tunnel/](http://0.0.0.0:4567/develop/infra/phoenix-lab-ssh-spice-tunnel/)
* [/develop/infra/phoenix-lab-storage-hosts/](http://0.0.0.0:4567/develop/infra/phoenix-lab-storage-hosts/)
* [/develop/release-management/features/storage/cinder-integration/](http://0.0.0.0:4567/develop/release-management/features/storage/cinder-integration/)
* [/develop/release-management/features/ux/detailedhostpmmultipleagents/](http://0.0.0.0:4567/develop/release-management/features/ux/detailedhostpmmultipleagents/)
* [/develop/release-management/releases/3.3.2/testing/](http://0.0.0.0:4567/develop/release-management/releases/3.3.2/testing/)
* [/documentation/admin-guide/administration-guide/](http://0.0.0.0:4567/documentation/admin-guide/administration-guide/)

**Comment by garrett** [comment]
At a high level overview, this looks like this _fixes_ the codeblocks — I'll merge it in and submit another one to review & optimize code blocks (which might even affect additional pages).

**Pull request merged**
