### PR TITLE
Adding Hyper Expert, LLC to professional services

### PR DESCRIPTION
**Pull request by hyperexpert**
Adding Hyper Expert, LLC to the list of Professional Services and Integrators. Hyper Expert relies heavily on oVirt to provide IT Management Solutions and Cloud Services. We contribute to the oVirt and Linux community by participating in mailing lists, forums, and submitting bug reports.

I confirm that this pull request was submitted according to the contribution guidelines: @hyperexpert

### CODE REVIEW

**Comment by gregsheremeta** [comment]
needs approval from @sandrobonazzola

**Comment by sandrobonazzola** [comment]
1842 files changed, can you please rebase so it will be possible to review the patch?

**Comment by gregsheremeta** [comment]
[ rebased ]

**Comment by doron-fediuck** [comment]
@hyperexpert can you provide some reference to your substantial contribution?
Let's say a list of the last 10-15 BZs you reported or a feature contributed to oVirt code base?

**Comment by doron-fediuck** [comment]
Closing for lack of activity.

**Pull request closed without merging**
