### PR TITLE
add_doc_files_2_gitignore Added doc files and directories to .gitignore.

### PR DESCRIPTION
**Pull request by stoobie**
Changes proposed in this pull request:

- Added files and directories to .gitignore. These files and directories are generated during so documentation testing.

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @stoobie 

This pull request needs review by: @sandrobonazzola

### CODE REVIEW

**Comment by apinnick** [comment]
@stoobie Can I close this PR?

**Comment by stoobie** [comment]
@apinnick I suggest merging it. I created it because every time I generated HTML content on my local machine, git wanted to add all those generated files.

**Comment by stoobie** [comment]
@sandrobonazzola or someone else needs to approve it, though.

**Comment by apinnick** [comment]
@stoobie I see now. You wanted to add some things to .gitignore so that preview builds would not be added to the commit. No problem. This PR has some conflicts because you opened it a while ago. I'll close this PR and open a new one for .gitignore.

**Pull request closed without merging**
