### PR TITLE
Fixed markdown_to_html() matching

### LINKED ISSUE #1025: 'httpd' wierd behaviour
### Description of the problem

In [1], 'httpd' appears only once, and is surrounded by angle brackets, '```<httpd>```'.

In the page source code [2], as well as in github's rendering of it, it appears three times, none surrounded.

Something causes two occurrences to disappear and one to be surrounded. Not sure what. Please fix :-)

Thanks!

[1] https://www.ovirt.org/documentation/how-to/migrate-pki-to-sha256/
[2] https://github.com/oVirt/ovirt-site/blob/master/source/documentation/how-to/migrate-pki-to-sha256.html.md

### PR DESCRIPTION
**Pull request by duck-rh**
fixes #1025

### CODE REVIEW

**Comment by duck-rh** [comment]
You're right, I must have made a mistake just before pushing. Thanks.

**Comment by didib** [comment]
Looks ok to me.

**Comment by duck-rh** [comment]
thanks for the review

**Comment by didib** [comment]
Thanks for the fix! :-)

**Pull request merged**
