### PR TITLE
Update metrics-store-schema.html.md

### PR DESCRIPTION
**Pull request by sradco**
Fixes issue :
Moved metrics name to the beginning of the tables and fixed bug in the NFS table.

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sradco

This pull request needs review by: @mykaul

### CODE REVIEW

**Comment by sradco** [comment]
@mykaul Hi, Please review.

**Comment by mykaul** [comment]
@sradco - you have conflicts, please resolve.

**Comment by sradco** [comment]
@mykaul resolved conflicts.

**Comment by mykaul** [comment]
@sradco - it still says 'This branch cannot be rebased due to conflicts'

**Pull request merged**
