### PR TITLE
schema - adding metrics schema files to upstream

### PR DESCRIPTION
**Pull request by emarcusRH**
Changes proposed in this pull request:

- adding metrics schema files to upstream library in order to include in the Administration_guide/chap-monitoring_and_observability chapter

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @emarcusRH

This pull request needs review by: @sradco / @sandrobonazzola

### CODE REVIEW

**Comment by emarcusRH** [comment]
@sandrobonazzola hi Sandro, I think I may have gotten my setup wrong, and this got pushed directly to the master repo instead of my forked repo (git@github.com:emarcusRH/ovirt-site.git).
Is it possible to use this PR directly? 
Could you or @sradco review this and merge if it is ok?

**Comment by sandrobonazzola** [comment]
@emarcusRH ok for me. Waiting for CI to test the PR before merging.

**Comment by emarcusRH** [comment]
> @emarcusRH ok for me. Waiting for CI to test the PR before merging.

Thanks, can you test if my ifdef conditional statement works correctly in the chap-monitoring_and_observability.adoc filee that I updated to include the Metrics_Schema.adoc?

**Comment by sandrobonazzola** [comment]
Looks good to me when rendered for oVirt site, didn't try it on RHV docs.

**Review by sandrobonazzola — APPROVED** [review]

**Comment by sandrobonazzola** [comment]
Looks like there are some troubles with the CI, trying to get them solved.

**Comment by sandrobonazzola** [comment]
closing and reopening to re-trigger CI

**Pull request merged**
