### PR TITLE
Adding SkyVirt case study

### PR DESCRIPTION
**Pull request by ARNESolutionLLP**
Changes proposed in this pull request:

There is no viable alternative for real-world experience. That’s the motivation we made the SkyVirt® - (Real-Time Emulation)Training Platform-[ Tarun Kumar Kushwaha](https://skyvirt.tech/TarunKumar) (Founder)
SkyVirt® is a Virtual Training Environment(VTE) designed as a real-time emulation platform for conducting the training for full spectrum IT Infrastructure, Cyber Security & Digital Forensics. 
Four training delivery methods are utilizing within the SkyVirt® to drive Cyber Warrior proficiency:
•	Hyper-Realistic-Based Modules 
•	Self-Paced Modules
•	Team-Based Dynamic Modules
•	Custom Module Assessments and Delivery
For  SkyVirt®, we are using pure and core Open-Source technology like Ovirt, CEPH. We have no doubt about Ovirt because It’s fully sponsored by renowned multinational software company RedHat and many others. 
Note: Till now, we have successfully hosted 2000+ VMs on the ovirt cluster.

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
@ARNESolutionLLP  Can you please edit your PR, deleting the "Fixes issue" line, describing the contetn of the request (adding a user story) and signing your acceptance of contribution guidelines?

**Comment by ARNESolutionLLP** [comment]
> @ARNESolutionLLP Can you please edit your PR, deleting the "Fixes issue" line, describing the contetn of the request (adding a user story) and signing your acceptance of contribution guidelines?

Done

**Comment by sandrobonazzola** [comment]
I submitted this contribution to oVirt Board for review. As a first step "For this to become a relevant oVirt reference we need a well written case study, explaining how oVirt is being used by their institute and how it is being leveraged for education."
See as example https://ovirt.org/community/user-stories/RCC-case-study.html .
I would be happy to work with you preparing it.

**Comment by ARNESolutionLLP** [comment]
final case study attached with this
[SkyVirtCommunityfinal.docx](https://github.com/oVirt/ovirt-site/files/5550814/SkyVirtCommunityfinal.docx)

**Comment by sandrobonazzola** [comment]
@ARNESolutionLLP can you please review?

**Comment by sandrobonazzola** [comment]
closing due to inactivity, no response over email direct contact

**Pull request closed without merging**
