### PR TITLE
Create hosted-engine-migration-to-4.0.md

### PR DESCRIPTION
**Pull request by rgolangh**
Adding the feature page for RFE https://bugzilla.redhat.com/show_bug.cgi?id=1319457 
Support migrating hosted engine to 4.0

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
Please sync with @tiraboschi about this. :-1:

**Comment by doron-fediuck** [comment]
@rgolangh any updates?

**Comment by rgolangh** [comment]
I think I'll leave this for @tiraboschi to update.. The impl details have diverged and it would be best  if @tiraboschi would add them.

**Comment by tiraboschi** [comment]
I write this one:
https://github.com/oVirt/ovirt-site/pull/296/commits/d8aaa227e0a304b493d2a281bf34fe4eaef48b28

**Comment by rgolangh** [comment]
no longer relevant.

**Pull request closed without merging**
