### PR TITLE
Documentation for using containers with oVirt

### PR DESCRIPTION
**Pull request by leni1**
As part of the Outreachy project for oVirt, we are trying to document using oVirt with several other open source software components in software containers as outlined [here](http://www.ovirt.org/community/activities/outreachy/).

Changes proposed in this pull request:

- Addition of a folder to hold the documentation proposed above. 
- Document detailing the aims behind the proposed documentation
- Sample documentation for using PostgreSQL in a container with the oVirt Engine. 
- Sample documentation for using ManageIQ in a container with the oVirt Engine.

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md):  @leni1

This pull request needs review by: @jasonbrooks

### CODE REVIEW

**Comment by jasonbrooks** [comment]
I think we need title and author metadata, and some headings, like in https://raw.githubusercontent.com/leni1/ovirt-site/e21140df850b76bfc39fc90747d16b1047ec0b27/source/documentation/how-to/troubleshooting/troubleshooting-nfs-storage-issues.html.md

**Comment by leni1** [comment]
@jasonbrooks added the recommended modifications.

**Comment by jasonbrooks** [comment]
Looks good to me

**Comment by JohnMarksRH** [comment]
@jasonbrooks Looks good, though I think it could do with a more detailed introduction, particularly the "what" and "Why".

**Comment by leni1** [comment]
@jasonbrooks @JohnMarksRH apologies that I've taken so long to work on this. Let me know if the revised "about" document answers the What and Why better.

**Comment by jasonbrooks** [comment]
[Outreachy](https://trello.com/c/mUeLRKAq/2-outreachy)

**Comment by jasonbrooks** [comment]
@JohnMarksRH can we merge this?

**Pull request merged**
