### PR TITLE
Extracted non-CoC info from community guidelines to a separate page

### PR DESCRIPTION
**Pull request by thatdocslady**
Related to CoC PR: https://github.com/oVirt/ovirt-site/pull/30

This PR adds a new page with information on mailing list, IRC, BZ, and Gerrit guidelines. The information was previously mixed in with CoC info under Community Guidelines, so now there are two separate pages (the CoC is still in review).

### CODE REVIEW

**Comment by bproffitt** [comment]
@thatdocslady I understand the need the for this page, but it is a duplicate of http://www.ovirt.org/community/about/community-guidelines/ Why two versions of the same page?

**Comment by thatdocslady** [comment]
@bproffitt this page is intended to replace the previous community guidelines page, in conjunction with the new CoC.

**Comment by thatdocslady** [comment]
I see that @mykaul announced the new CoC and guidelines, is this PR even relevant anymore? Maybe we can close it or have someone process it further as needed?

**Comment by bproffitt** [comment]
Closed due to closure of another PR on this issue.

**Pull request closed without merging**
