### PR TITLE
Create a dynamic page from the feature pages

### PR DESCRIPTION
**Pull request by rgolangh**
Much like the original static page a directory is
generating a heading and each '*.html.md' undereath it
creats a list item with a anchor:

tree release-management/features
virt
 ->
    some_feature_1.html.md
infra
    some_feature_2.html.md
...
_____________________________

<h3>Virt</h3>
<ul>
  <li><a href="../some_feature_1.html.md">Some Feature 1</a></li>
</ul>
<h3>Infra</h3>
<ul>
  <li><a href="../some_feature_2.html.md">Some Feature 2</a></li>
</ul>

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @mention yourself to sign)

@rgolanghg

@lgh2 @sandrobonazzola @rollandf

### CODE REVIEW

**Comment by rgolangh** [comment]
ping anyone?

**Comment by lwrigh** [comment]
@rgolangh Can you attach a screenshot or a gif of it?

**Comment by rgolangh** [comment]
image

**Comment by sandrobonazzola** [comment]
@lwrigh what do you think? looks good to me. Can we merge?

**Comment by duck-rh** [comment]
I agree with doing things dynamic but in this case this means adding custom Ruby code and if we want to migrate to Jekyll one day then it's going to make things difficult. I'm just beginning to look at it now (now that the blog has migrated), but we should have a way to replace these snippets in Liquid or some other way. Could such kind of changes not wait?

**Comment by lwrigh** [comment]
It looks good to me!

**Comment by sandrobonazzola** [comment]
Merged, thanks!

**Comment by rgolangh** [comment]
Thanks!
And the nice thing is that we can see a nice and long list of features(even though pages/features are probably outdated) - the count it roughly **420 feature pages**

**Comment by duck-rh** [comment]
@sandrobonazzola thanks for taking my comment into account

**Comment by rgolangh** [comment]
@lwrigh you know of more pages which totally static that we can make dynamic? after this PR its rougly copy-paste engineering and we have it done.

@duck-rh I'd prefer migrating the ruby code to jekyl and not wait till we do it in an unknown date.
This website is in not in good condition and I think baby steps to improve it should be encouraged.

**Comment by lwrigh** [comment]
@rgolangh I can't name any off hand but I can do a quick search to see if I find any more common pages that are static and would benefit from being dynamic.

**Comment by duck-rh** [comment]
@rgolangh As much as I understand, all the work around the blog migration is done and the cleanup done too (including quite some Ruby code), so this is a real first step to simplify things and work on the migration. I'm going to work on it, we already are using Jekyll on other projects, but the more complex it is the later it's going to be for sure. Also I would rather avoid porting the Ruby spaghetti we have today over to Jekyll, there's probably cleaner ways to do most of it. Well, I guess nobody really cares…

**Comment by rgolangh** [comment]
> Well, I guess nobody really cares…
I can't back up this feeling you have.
I think ovirt contributers and stake-holders are not aware of what's going on.
Are you sharing with the mailing list the efforts around it? we would love to hear and help.
When we need something we open jira tickets for ovirt-infra and issues here if needed, and
send patches.

**Comment by duck-rh** [comment]
@rgolangh there was such kind of discussion in the past, multiple times, and I participated. I also raised the topic slightly in tickets like OVIRT-2652 for eg, as well as in the Infra Team meeting. It's true I did not start a wide discussion as most people would expect a perfectly defined plan and deadline which I cannot provide now. Let me open a thread and see how it goes then.

**Pull request merged**
